FROM dockerfile/ubuntu

ADD udp.conf /docker-logstash

WORKDIR /docker-logstash
RUN curl -O https://download.elasticsearch.org/logstash/logstash/logstash-1.4.0.tar.gz
RUN tar zxvf logstash-1.4.0.tar.gz

RUN curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.1.tar.gz
RUN tar zxvf elasticsearch-1.0.1.tar.gz

CMD ./run.sh